# Generated by Django 4.2.24 on 2025-09-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonreport',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.lesson'),
        ),
    ]
